'use client'
import { FormEvent, useLayoutEffect, useRef, useState } from 'react'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import EnergyScene from './EnergyScene'
import { fadeUp, maskReveal, scaleReveal } from '../lib/motion'
gsap.registerPlugin(ScrollTrigger)
const projects = { Residencial: ['Casa Litoral', 'Ubatuba · 8,2 kWp', 'Uma solução que acompanha a arquitetura, não a invade.'], Comercial: ['Espaço Horizonte', 'Campinas · 42 kWp', 'Energia previsível para uma operação que não pode parar.'], Industrial: ['Unidade Norte', 'Jundiaí · 128 kWp', 'Escala, engenharia e acompanhamento em cada etapa.'] }
const faqs = ['Energia solar realmente reduz a conta?', 'Quanto tempo leva uma instalação?', 'Meu imóvel precisa ter determinadas condições?', 'Como funciona a manutenção?', 'O sistema continua funcionando em dias nublados?', 'Como é feita a análise do projeto?']
export default function SolarExperience() {
 const root = useRef<main>(null); const [activeProject,setActiveProject] = useState<keyof typeof projects>('Residencial'); const [open,setOpen]=useState<number|null>(null); const [consumption,setConsumption]=useState(650); const [property,setProperty]=useState('Residencial'); const [city,setCity]=useState('São Paulo')
 const estimate = Math.round(consumption * .72); const annual = estimate * 12
 useLayoutEffect(() => { if (matchMedia('(prefers-reduced-motion: reduce)').matches) return; const ctx=gsap.context(()=>{
   const intro=gsap.timeline({defaults:{ease:'power4.out'}}); intro.from('.nav',{autoAlpha:0,y:-18,duration:.7}).from('.hero-kicker',{autoAlpha:0,y:20,duration:.7},'-.35'); maskReveal('.hero-title .line',{stagger:.1}).duration(1.08); intro.from('.hero-copy',{autoAlpha:0,y:28,duration:.7},'-.62').from('.hero-actions',{autoAlpha:0,scale:.95,duration:.6},'-.45').from('.scene-wrap',{autoAlpha:0,scale:.72,rotation:-9,duration:1.5,ease:'power3.out'},'-.9')
   gsap.to('.nav',{backgroundColor:'rgba(8,12,16,.86)',backdropFilter:'blur(14px)',borderBottomColor:'rgba(255,255,255,.12)',paddingTop:17,paddingBottom:17,scrollTrigger:{start:'top -50',end:'top -150',scrub:true}}); gsap.to('.hero-content',{y:-70,opacity:.3,scrollTrigger:{trigger:'.hero',start:'35% top',end:'bottom top',scrub:true}}); gsap.to('.scene-wrap',{x:120,y:-40,scale:.72,rotation:22,scrollTrigger:{trigger:'.hero',start:'28% top',end:'bottom top',scrub:true}})
   gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>fadeUp(el,{scrollTrigger:{trigger:el,start:'top 84%'}})); scaleReveal('.problem-number',{scrollTrigger:{trigger:'.problem-number',start:'top 78%'}})
   gsap.from('.process-step',{autoAlpha:0,x:-34,stagger:.18,duration:.7,scrollTrigger:{trigger:'.process',start:'top 75%'}}); gsap.from('.benefit',{autoAlpha:0,y:50,stagger:.12,duration:.75,scrollTrigger:{trigger:'.benefits',start:'top 70%'}})
   const story=gsap.timeline({scrollTrigger:{trigger:'.value-story',start:'top top',end:'+=130%',pin:true,scrub:true}}); story.to('.value-one',{autoAlpha:0,y:-40}).fromTo('.value-two',{autoAlpha:0,y:35},{autoAlpha:1,y:0},'<').to('.value-two',{autoAlpha:0,y:-40},'+=.5').fromTo('.value-three',{autoAlpha:0,y:35},{autoAlpha:1,y:0},'<')
 },root); return()=>ctx.revert()},[])
 function updateSimulation(e: FormEvent){e.preventDefault(); gsap.fromTo('.sim-result',{scale:.96,autoAlpha:.5},{scale:1,autoAlpha:1,duration:.5,ease:'power3.out'}); gsap.fromTo('.bar-fill',{scaleX:.3},{scaleX:1,duration:.7,ease:'power3.out'})}
 return <main ref={root}>
  <nav className="nav"><a className="brand" href="#inicio"><strong>THIAGO</strong><span>ENERGIA SOLAR</span></a><div className="nav-links"><a href="#solucoes">Soluções</a><a href="#processo">Como funciona</a><a href="#beneficios">Benefícios</a><a href="#projetos">Projetos</a><a href="#faq">FAQ</a></div><a className="nav-cta" href="#simulador">Simular economia <b>↗</b></a></nav>
  <section className="hero" id="inicio"><div className="grid-bg"/><div className="hero-content"><p className="eyebrow hero-kicker">ENERGIA INTELIGENTE PARA UM FUTURO MAIS EFICIENTE</p><h1 className="hero-title"><span className="clip"><span className="line">Transforme a luz</span></span><span className="clip"><span className="line">do sol em <em>liberdade.</em></span></span></h1><p className="hero-copy">Reduza sua dependência da rede elétrica com uma solução solar projetada para gerar economia por muitos anos.</p><div className="hero-actions"><a className="button" href="#simulador">Calcular minha economia <span>→</span></a><a className="text-link" href="#solucoes">Conhecer a solução <span>↓</span></a></div></div><div className="scene-wrap"><EnergyScene/></div><p className="scroll-hint">ROLE PARA DESCOBRIR <i/></p></section>
  <section className="problem section" id="solucoes"><div><p className="eyebrow reveal">UMA DESPESA PODE VIRAR ESTRUTURA</p><h2 className="reveal">Sua conta de energia<br/>não precisa continuar <em>crescendo.</em></h2></div><div className="problem-side reveal"><p>A energia que você consome todos os meses representa uma despesa recorrente. A energia solar transforma parte desse custo em investimento na sua própria estrutura.</p><div className="problem-number"><strong>12</strong><sup>x</sup><span>meses acompanhando uma conta que poderia estar trabalhando a seu favor.</span></div></div></section>
  <section className="value-story"><div className="value-header"><p className="eyebrow">O QUE REALMENTE ESTÁ EM JOGO</p><span>01—03</span></div><article className="value-item value-one"><p>01</p><h2>Você não compra<br/>painéis. Você compra <em>controle.</em></h2><span>ECONOMIA</span><small>Mais eficiência no uso da energia.</small></article><article className="value-item value-two hidden"><p>02</p><h2>Um custo menor.<br/>Uma relação mais <em>previsível.</em></h2><span>PREVISIBILIDADE</span><small>Menor exposição às variações da conta de luz.</small></article><article className="value-item value-three hidden"><p>03</p><h2>Energia que também<br/>agrega <em>valor.</em></h2><span>VALOR</span><small>Uma estrutura energética que valoriza o imóvel.</small></article><div className="value-orbit"><i/><i/><b>☀</b></div></section>
  <section className="energy-story"><div className="energy-copy"><p className="eyebrow">SISTEMA EM MOVIMENTO</p><h2>Da luz à<br/><em>economia.</em></h2><p>Captação, geração, conversão e consumo integrados em um único sistema projetado para o seu imóvel.</p><div className="energy-states"><span>01 CAPTAÇÃO</span><span>02 GERAÇÃO</span><span>03 CONVERSÃO</span><span>04 CONSUMO</span><span>05 ECONOMIA</span></div></div><div className="energy-scene"><EnergyScene detail/></div></section>
  <section className="process section" id="processo"><p className="eyebrow reveal">UM PROCESSO CLARO, DO INÍCIO À GERAÇÃO</p><h2 className="reveal">Do sol à economia<br/>em quatro etapas.</h2><div className="process-line"/><div className="process-steps">{[['01','Análise','Entendimento do imóvel e do consumo.'],['02','Projeto','Dimensionamento preciso do sistema.'],['03','Instalação','Implementação profissional da solução.'],['04','Geração','O sistema começa a produzir energia.']].map(x=><article className="process-step" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <section className="simulator section" id="simulador"><div className="sim-copy"><p className="eyebrow">SIMULAÇÃO DEMONSTRATIVA</p><h2>Quanto você poderia <em>economizar?</em></h2><p>Use uma estimativa de consumo para visualizar o potencial do seu imóvel.</p></div><form onSubmit={updateSimulation}><label>Consumo mensal <div className="range-value">{consumption} kWh</div><input type="range" min="200" max="1800" step="50" value={consumption} onChange={e=>setConsumption(+e.target.value)}/></label><label>Tipo de imóvel<select value={property} onChange={e=>setProperty(e.target.value)}><option>Residencial</option><option>Comercial</option><option>Industrial</option></select></label><label>Cidade<select value={city} onChange={e=>setCity(e.target.value)}><option>São Paulo</option><option>Campinas</option><option>Santos</option></select></label><button className="button">Atualizar estimativa <span>→</span></button></form><div className="sim-result"><div className="result-main"><span>Economia estimada / mês</span><strong>R$ {estimate.toLocaleString('pt-BR')}</strong><div className="chart"><i className="bar-fill" style={{width:`${Math.min(88,25+consumption/24)}%`}}/></div></div><div><span>Economia anual</span><b>R$ {annual.toLocaleString('pt-BR')}</b></div><div><span>Perfil</span><b>{property}</b></div><small>Valores demonstrativos. As estimativas dependem de consumo, localização, tarifa e dimensionamento do sistema.</small><a className="text-link" href="#contato">Quero uma análise personalizada <span>↗</span></a></div></section>
  <section className="benefits" id="beneficios"><div className="benefits-heading"><p className="eyebrow">O QUE MUDA QUANDO A ENERGIA TRABALHA POR VOCÊ</p><h2>Mais do que<br/><em>energia.</em></h2></div><div className="benefit-list">{['Redução de custos','Independência energética','Previsibilidade','Tecnologia','Sustentabilidade','Valorização do imóvel'].map((b,i)=><div className="benefit" key={b}><span>0{i+1}</span><strong>{b}</strong><i>↗</i></div>)}</div></section>
  <section className="projects section" id="projetos"><p className="eyebrow reveal">PROJETOS SELECIONADOS</p><h2 className="reveal">Energia pensada para<br/>cada <em>espaço.</em></h2><div className="project-tabs">{Object.keys(projects).map(p=><button className={activeProject===p?'active':''} onClick={()=>setActiveProject(p as keyof typeof projects)} key={p}>{p}</button>)}</div><article className="project-display"><div className={'project-image '+activeProject.toLowerCase()}><span>TES</span><i/></div><div className="project-info"><p>{projects[activeProject][1]}</p><h3>{projects[activeProject][0]}</h3><span>{projects[activeProject][2]}</span><a href="#contato" className="text-link">Ver detalhes <b>→</b></a></div></article></section>
  <section className="engineering section"><p className="eyebrow">DIFERENCIAL TÉCNICO</p><h2>Engenharia antes<br/>da <em>instalação.</em></h2><div className="flow">{['Análise','Dimensionamento','Projeto','Instalação','Monitoramento'].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b></div>)}</div></section>
  <section className="monitor section"><div><p className="eyebrow">VISIBILIDADE PARA DECIDIR MELHOR</p><h2>Energia sob<br/><em>controle.</em></h2><p>Uma demonstração da leitura simples que transforma dados de geração em tranquilidade.</p></div><div className="dashboard"><div className="dash-top"><span>GERAÇÃO</span><b>8.4 kWh</b><i>● AO VIVO</i></div><svg viewBox="0 0 400 170" aria-label="Gráfico demonstrativo de geração"><path d="M0 150 C35 145 50 108 82 120 S120 77 152 92 S200 35 228 61 S275 49 303 78 S350 12 400 25" fill="none" stroke="#ffc94d" strokeWidth="3"/><path d="M0 150 C35 145 50 108 82 120 S120 77 152 92 S200 35 228 61 S275 49 303 78 S350 12 400 25 V170 H0 Z" fill="url(#g)" opacity=".4"/><defs><linearGradient id="g" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#ffc94d"/><stop offset="1" stopColor="#ffc94d" stopOpacity="0"/></linearGradient></defs></svg><div className="dash-bottom"><span>CONSUMO <b>3.1 kWh</b></span><span>ECONOMIA <b>R$ {estimate}</b></span><span>DESEMPENHO <b>98.6%</b></span></div></div></section>
  <section className="testimonials section"><p className="eyebrow">QUANDO A ENERGIA COMEÇA A TRABALHAR POR VOCÊ</p><h2>Decisões que<br/><em>fazem sentido.</em></h2><div className="quotes"><article><p>“A análise deixou claro que não estávamos apenas reduzindo uma conta. Estávamos criando previsibilidade.”</p><span>Mariana R. · Campinas</span><small>Residencial</small></article><article><p>“O cuidado com o projeto fez toda diferença na nossa decisão.”</p><span>Daniel F. · São Paulo</span><small>Comercial</small></article></div></section>
  <section className="faq section" id="faq"><p className="eyebrow">ANTES DE COMEÇAR, ALGUMAS RESPOSTAS</p><h2>O que você quer<br/><em>entender?</em></h2><div className="faq-list">{faqs.map((q,i)=><button key={q} className={open===i?'open':''} onClick={()=>setOpen(open===i?null:i)}><span>{q}</span><b>{open===i?'−':'+'}</b><p>{i===0?'Sim. A redução depende de fatores como perfil de consumo, tarifa local, dimensão do sistema e condições do imóvel. A análise personalizada mostra o potencial do seu caso.':'A resposta depende da análise técnica do imóvel. Nossa equipe explica cada cenário com clareza antes de qualquer decisão.'}</p></button>)}</div></section>
  <section className="final-cta" id="contato"><div><p className="eyebrow">O PRÓXIMO PASSO É SIMPLES</p><h2>O próximo ciclo da sua energia <em>começa aqui.</em></h2><p>Descubra quanto seu imóvel pode gerar e transforme sua relação com a energia.</p><div className="hero-actions"><a className="button" href="mailto:contato@thiagoenergia.com">Calcular minha economia <span>→</span></a><a className="text-link" href="mailto:contato@thiagoenergia.com">Falar com um especialista <span>↗</span></a></div></div><div className="final-scene"><EnergyScene detail/></div></section>
  <footer><a className="brand" href="#inicio"><strong>THIAGO</strong><span>ENERGIA SOLAR</span></a><div><a href="#solucoes">Soluções</a><a href="#projetos">Projetos</a><a href="#faq">FAQ</a><a href="mailto:contato@thiagoenergia.com">Contato</a></div><p>© 2026 Thiago Energia Solar. Conteúdo demonstrativo. Resultados variam conforme o projeto.</p></footer>
 </main>
}
