'use client'
import { FormEvent, useLayoutEffect, useRef, useState } from 'react'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import EnergyScene from './EnergyScene'
import { fadeUp, maskReveal, scaleReveal } from '../lib/motion'
gsap.registerPlugin(ScrollTrigger)
const faqs = ['Energia solar realmente reduz a conta?', 'Quanto custa um sistema de energia solar?', 'Meu imóvel precisa ter determinadas condições?', 'Como funciona a manutenção?', 'O sistema continua funcionando em dias nublados?', 'Como vocês definem o sistema ideal para cada imóvel?']
const tariffByState = {
 RO: { state: 'Rondônia', distributor: 'Energisa Rondônia', tariff: .84139, reference: 'ANEEL REH 3.560/2025' },
 MT: { state: 'Mato Grosso', distributor: 'Energisa Mato Grosso', tariff: .73419, reference: 'ANEEL REH 3.581/2026' },
} as const
const money = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'})
const whatsappNumber=(process.env.NEXT_PUBLIC_WHATSAPP_NUMBER||'556992755805').replace(/\D/g,'')
const contactEmail='contato@thiagoenergia.com'

export default function SolarExperience() {
 const root = useRef<HTMLElement>(null); const [open,setOpen]=useState<number|null>(null); const [monthlyBill,setMonthlyBill]=useState(500); const [property,setProperty]=useState('Residencial'); const [state,setState]=useState<keyof typeof tariffByState>('RO'); const [connection,setConnection]=useState(50); const [leadName,setLeadName]=useState(''); const [leadPhone,setLeadPhone]=useState(''); const [leadCity,setLeadCity]=useState('')
 const tariffInfo=tariffByState[state]; const tariff=tariffInfo.tariff; const estimatedConsumption=Math.round(monthlyBill/tariff); const minimumBill=connection*tariff; const solarBill=Math.max(minimumBill,monthlyBill*.1); const estimate=Math.max(0,Math.round(monthlyBill-solarBill)); const annual=estimate*12; const savingPercent=monthlyBill?Math.round(estimate/monthlyBill*100):0
 useLayoutEffect(() => { if (matchMedia('(prefers-reduced-motion: reduce)').matches) return; const ctx=gsap.context(()=>{
   const intro=gsap.timeline({defaults:{ease:'power4.out'}}); intro.from('.nav',{autoAlpha:0,y:-18,duration:.7}).from('.hero-kicker',{autoAlpha:0,y:20,duration:.7},'-.35'); maskReveal('.hero-title .line',{stagger:.1}).duration(1.08); intro.from('.hero-copy',{autoAlpha:0,y:28,duration:.7},'-.62').from('.hero-actions',{autoAlpha:0,scale:.95,duration:.6},'-.45').from('.scene-wrap',{autoAlpha:0,scale:.72,rotation:-9,duration:1.5,ease:'power3.out'},'-.9')
   gsap.to('.nav',{backgroundColor:'rgba(8,12,16,.86)',backdropFilter:'blur(14px)',borderBottomColor:'rgba(255,255,255,.12)',paddingTop:17,paddingBottom:17,scrollTrigger:{start:'top -50',end:'top -150',scrub:true}}); gsap.to('.hero-content',{y:-70,opacity:.3,scrollTrigger:{trigger:'.hero',start:'35% top',end:'bottom top',scrub:true}}); gsap.to('.scene-wrap',{x:120,y:-40,scale:.72,rotation:22,scrollTrigger:{trigger:'.hero',start:'28% top',end:'bottom top',scrub:true}})
   gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>fadeUp(el,{scrollTrigger:{trigger:el,start:'top 84%'}})); scaleReveal('.problem-number',{scrollTrigger:{trigger:'.problem-number',start:'top 78%'}})
   gsap.from('.process-step',{autoAlpha:0,x:-34,stagger:.18,duration:.7,scrollTrigger:{trigger:'.process',start:'top 75%'}}); gsap.from('.benefit',{autoAlpha:0,y:50,stagger:.12,duration:.75,scrollTrigger:{trigger:'.benefits',start:'top 70%'}})
 },root); return()=>ctx.revert()},[])
 function updateSimulation(e: FormEvent){e.preventDefault(); gsap.fromTo('.sim-result',{scale:.96,autoAlpha:.5},{scale:1,autoAlpha:1,duration:.5,ease:'power3.out'}); gsap.fromTo('.bar-fill',{scaleX:.3},{scaleX:1,duration:.7,ease:'power3.out'})}
 function submitLead(e: FormEvent){e.preventDefault(); const message=`Olá! Meu nome é ${leadName}. Moro em ${leadCity}/${state}, meu WhatsApp é ${leadPhone} e minha conta média é ${money.format(monthlyBill)}. Gostaria de receber uma análise gratuita.`; if(whatsappNumber){window.open(`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer')}else{window.location.href=`mailto:${contactEmail}?subject=${encodeURIComponent('Análise gratuita de energia solar')}&body=${encodeURIComponent(message)}`}}
 return <main ref={root}>
  <nav className="nav"><a className="brand" href="#inicio"><strong>THIAGO</strong><span>ENERGIA SOLAR</span></a><div className="nav-links"><a href="#solucoes">Soluções</a><a href="#processo">Como funciona</a><a href="#simulador">Simulador</a><a href="#cobertura">Atendimento</a><a href="#faq">FAQ</a></div><a className="nav-cta" href="#contato">Pedir análise <b>↗</b></a></nav>
  <section className="hero" id="inicio"><div className="grid-bg"/><div className="hero-content"><p className="eyebrow hero-kicker">ENERGIA SOLAR PENSADA PARA A SUA REALIDADE</p><h1 className="hero-title"><span className="clip"><span className="line">Transforme o sol</span></span><span className="clip"><span className="line">em <em>economia.</em></span></span></h1><p className="hero-copy">Entenda o seu consumo, encontre uma solução adequada para o seu imóvel e comece a produzir sua própria energia.</p><div className="hero-actions"><a className="button" href="#simulador">Quero entender meu potencial <span>→</span></a><a className="text-link" href="#solucoes">Conhecer a solução <span>↓</span></a></div></div><div className="scene-wrap"><EnergyScene/></div><p className="scroll-hint">ROLE PARA DESCOBRIR <i/></p></section>
  <section className="problem section" id="solucoes"><div><p className="eyebrow reveal">UMA DESPESA QUE PODE VIRAR INVESTIMENTO</p><h2 className="reveal">Sua conta de energia<br/>não precisa ser só <em>despesa.</em></h2></div><div className="problem-side reveal"><p>Você paga pela energia todos os meses. A energia solar permite transformar parte desse gasto em geração própria, com uma solução pensada para o seu consumo e para o seu imóvel.</p><div className="problem-number"><strong>12</strong><sup>x</sup><span>uma despesa que faz parte da sua rotina e que pode ser repensada com energia solar.</span></div></div></section>
  <section className="process section" id="processo"><p className="eyebrow reveal">UM PROCESSO CLARO, DO PRIMEIRO CONTATO À GERAÇÃO</p><h2 className="reveal">Entenda cada etapa<br/>antes de <em>decidir.</em></h2><div className="process-line"/><div className="process-steps">{[['01','Análise','Entender o consumo e as características do imóvel.'],['02','Projeto','Definir uma solução de acordo com a necessidade identificada.'],['03','Instalação','Colocar o projeto em prática de forma organizada.'],['04','Geração','O sistema passa a produzir energia para o imóvel.']].map(x=><article className="process-step" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <section className="simulator section" id="simulador"><div className="sim-copy"><p className="eyebrow">SIMULAÇÃO RÁPIDA</p><h2>Quanto da sua conta pode virar <em>economia?</em></h2><p>Escolha o estado e informe aproximadamente quanto você paga por mês. O cálculo usa automaticamente a tarifa da distribuidora.</p></div><form onSubmit={updateSimulation}><label>Valor médio da sua conta <div className="range-value">{money.format(monthlyBill)}</div><input type="range" min="100" max="5000" step="50" value={monthlyBill} onChange={e=>setMonthlyBill(+e.target.value)}/></label><label>Estado<select value={state} onChange={e=>setState(e.target.value as keyof typeof tariffByState)}><option value="RO">Rondônia</option><option value="MT">Mato Grosso</option></select></label><label>Tipo de imóvel<select value={property} onChange={e=>setProperty(e.target.value)}><option>Residencial</option><option>Comercial</option><option>Industrial</option></select></label><label>Tipo de ligação<select value={connection} onChange={e=>setConnection(+e.target.value)}><option value="30">Monofásica</option><option value="50">Bifásica</option><option value="100">Trifásica</option></select><small>Se não souber, deixe bifásica.</small></label><div className="tariff-source"><span>Tarifa identificada</span><b>{tariffInfo.distributor}</b><small>{money.format(tariff)}/kWh • {tariffInfo.reference}</small></div><button className="button">Calcular minha economia <span>→</span></button></form><div className="sim-result"><div className="result-main"><span>Você pode economizar aproximadamente</span><strong>{money.format(estimate)} por mês</strong><div className="chart"><i className="bar-fill" style={{width:`${savingPercent}%`}}/></div></div><div><span>Economia em 1 ano</span><b>{money.format(annual)}</b></div><div><span>Consumo estimado</span><b>{estimatedConsumption} kWh/mês</b></div><div><span>Conta informada</span><b>{money.format(monthlyBill)}</b></div><div><span>Conta residual estimada</span><b>{money.format(solarBill)}</b></div><div><span>Redução estimada</span><b>{savingPercent}%</b></div><small>Estimativa inicial com tarifa residencial regulada, sem bandeira tarifária e iluminação pública. O resultado final depende da fatura, incidência solar, telhado e dimensionamento do sistema.</small><a className="text-link" href="#contato">Quero receber uma análise gratuita <span>↗</span></a></div></section>
  <section className="benefits" id="beneficios"><div className="benefits-heading"><p className="eyebrow">O QUE VOCÊ BUSCA QUANDO ESCOLHE ENERGIA SOLAR</p><h2>Mais do que<br/><em>energia.</em></h2></div><div className="benefit-list">{['Economia na conta de energia','Geração própria','Mais previsibilidade','Tecnologia','Aproveitamento da energia solar','Uma solução pensada para o imóvel'].map((b,i)=><div className="benefit" key={b}><span>0{i+1}</span><strong>{b}</strong><i>↗</i></div>)}</div></section>
  <section className="coverage section" id="cobertura"><div><p className="eyebrow">ATENDIMENTO REGIONAL</p><h2>Energia solar em <em>Rondônia</em> e Mato Grosso.</h2><p>Atendimento para residências, comércios e propriedades que buscam reduzir a conta de energia com uma solução dimensionada para cada local.</p><a className="button" href="#contato">Consultar minha cidade <span>→</span></a></div><div className="coverage-states"><article><strong>RO</strong><span>Rondônia</span><small>Atendimento regional</small></article><article><strong>MT</strong><span>Mato Grosso</span><small>Consulte disponibilidade</small></article></div></section>
  <section className="assurance section"><p className="eyebrow">CLAREZA DO INÍCIO AO PÓS-VENDA</p><h2>O que você recebe<br/>antes de <em>decidir.</em></h2><div className="assurance-grid">{[['01','Análise da fatura','Dimensionamento baseado no consumo e nas condições do imóvel.'],['02','Projeto e homologação','Orientação sobre as etapas técnicas e o processo junto à distribuidora.'],['03','Proposta transparente','Equipamentos, garantias e prazo apresentados antes da contratação.'],['04','Acompanhamento','Suporte durante a instalação e orientação após a entrega.']].map(item=><article key={item[0]}><span>{item[0]}</span><h3>{item[1]}</h3><p>{item[2]}</p></article>)}</div></section>
  <section className="faq section" id="faq"><p className="eyebrow">ANTES DE COMEÇAR, ALGUMAS RESPOSTAS</p><h2>O que você precisa<br/><em>entender?</em></h2><div className="faq-list">{faqs.map((q,i)=><button key={q} className={open===i?'open':''} onClick={()=>setOpen(open===i?null:i)}><span>{q}</span><b>{open===i?'−':'+'}</b><p>{i===0?'Pode reduzir a conta de energia, mas o resultado depende do consumo, da tarifa, da localização, das condições do imóvel e do dimensionamento do sistema. Por isso, a análise do caso é importante.':i===1?'O investimento varia conforme o consumo, o imóvel e a solução necessária. Depois de entender esses fatores, é possível avaliar uma proposta adequada.':i===2?'As condições do imóvel precisam ser avaliadas para entender a viabilidade e o dimensionamento da solução.':i===3?'A manutenção e o acompanhamento dependem dos equipamentos e da solução instalada. Esses pontos devem ser explicados durante a apresentação do projeto.':i===4?'Sim. Os módulos continuam gerando energia com a radiação solar disponível, embora a produção possa ser menor em dias nublados.':'O sistema é definido a partir de informações como consumo, localização e características do imóvel. A ideia é dimensionar uma solução adequada ao caso.'}</p></button>)}</div></section>
  <section className="lead-section" id="contato"><div className="lead-copy"><p className="eyebrow">ANÁLISE GRATUITA</p><h2>Envie seus dados e descubra uma solução para o <em>seu imóvel.</em></h2><p>Sem compromisso. Usaremos essas informações apenas para entrar em contato e analisar sua conta de energia.</p></div><form className="lead-form" onSubmit={submitLead}><label>Seu nome<input required value={leadName} onChange={e=>setLeadName(e.target.value)} placeholder="Como podemos chamar você?"/></label><label>WhatsApp<input required inputMode="tel" value={leadPhone} onChange={e=>setLeadPhone(e.target.value)} placeholder="(00) 00000-0000"/></label><label>Sua cidade<input required value={leadCity} onChange={e=>setLeadCity(e.target.value)} placeholder="Cidade"/></label><label>Estado<select value={state} onChange={e=>setState(e.target.value as keyof typeof tariffByState)}><option value="RO">Rondônia</option><option value="MT">Mato Grosso</option></select></label><div className="lead-summary"><span>Conta média informada</span><b>{money.format(monthlyBill)}/mês</b></div><button className="button">Receber análise gratuita <span>→</span></button><small>Ao enviar, você autoriza o contato da Thiago Energia Solar sobre esta solicitação.</small></form></section>
  <a className="whatsapp-float" href={whatsappNumber?`https://wa.me/${whatsappNumber}?text=${encodeURIComponent('Olá! Gostaria de fazer uma simulação de energia solar.')}`:`mailto:${contactEmail}`} target={whatsappNumber?'_blank':undefined} rel="noreferrer" aria-label="Falar com a Thiago Energia Solar">{whatsappNumber?'WhatsApp':'Fale conosco'} <b>↗</b></a>
  <footer><a className="brand" href="#inicio"><strong>THIAGO</strong><span>ENERGIA SOLAR</span></a><div><a href="#solucoes">Soluções</a><a href="#simulador">Simulador</a><a href="#cobertura">Atendimento</a><a href="#faq">FAQ</a><a href="#contato">Contato</a></div><p>© 2026 Thiago Energia Solar. As informações e estimativas apresentadas podem variar conforme o consumo, o imóvel e o dimensionamento do sistema.</p></footer>
 </main>
}
