'use client'
import { FormEvent, useLayoutEffect, useRef, useState } from 'react'
import Image from 'next/image'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import EnergyScene from './EnergyScene'
import { fadeUp, maskReveal, scaleReveal } from '../lib/motion'
gsap.registerPlugin(ScrollTrigger)
const projects = { Residencial: ['Soluções residenciais', 'Para a sua casa', 'Um sistema pensado de acordo com o consumo e as características do imóvel.'], Comercial: ['Soluções comerciais', 'Para o seu negócio', 'Uma solução dimensionada para ajudar sua empresa a produzir a própria energia.'], Industrial: ['Soluções de maior escala', 'Para diferentes necessidades', 'Projetos dimensionados de acordo com o consumo e as características de cada instalação.'] }
const faqs = ['Energia solar realmente reduz a conta?', 'Quanto custa um sistema de energia solar?', 'Meu imóvel precisa ter determinadas condições?', 'Como funciona a manutenção?', 'O sistema continua funcionando em dias nublados?', 'Como vocês definem o sistema ideal para cada imóvel?']

export default function SolarExperience() {
 const root = useRef<HTMLElement>(null); const [activeProject,setActiveProject] = useState<keyof typeof projects>('Residencial'); const [open,setOpen]=useState<number|null>(null); const [consumption,setConsumption]=useState(650); const [property,setProperty]=useState('Residencial'); const [city,setCity]=useState('São Paulo')
 const estimate = Math.round(consumption * .72); const annual = estimate * 12
 useLayoutEffect(() => { if (matchMedia('(prefers-reduced-motion: reduce)').matches) return; const ctx=gsap.context(()=>{
   const intro=gsap.timeline({defaults:{ease:'power4.out'}}); intro.from('.nav',{autoAlpha:0,y:-18,duration:.7}).from('.hero-kicker',{autoAlpha:0,y:20,duration:.7},'-.35'); maskReveal('.hero-title .line',{stagger:.1}).duration(1.08); intro.from('.hero-copy',{autoAlpha:0,y:28,duration:.7},'-.62').from('.hero-actions',{autoAlpha:0,scale:.95,duration:.6},'-.45').from('.scene-wrap',{autoAlpha:0,scale:.72,rotation:-9,duration:1.5,ease:'power3.out'},'-.9')
   gsap.to('.nav',{backgroundColor:'rgba(8,12,16,.86)',backdropFilter:'blur(14px)',borderBottomColor:'rgba(255,255,255,.12)',paddingTop:17,paddingBottom:17,scrollTrigger:{start:'top -50',end:'top -150',scrub:true}}); gsap.to('.hero-content',{y:-70,opacity:.3,scrollTrigger:{trigger:'.hero',start:'35% top',end:'bottom top',scrub:true}}); gsap.to('.scene-wrap',{x:120,y:-40,scale:.72,rotation:22,scrollTrigger:{trigger:'.hero',start:'28% top',end:'bottom top',scrub:true}})
   gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>fadeUp(el,{scrollTrigger:{trigger:el,start:'top 84%'}})); scaleReveal('.problem-number',{scrollTrigger:{trigger:'.problem-number',start:'top 78%'}})
   gsap.from('.process-step',{autoAlpha:0,x:-34,stagger:.18,duration:.7,scrollTrigger:{trigger:'.process',start:'top 75%'}}); gsap.from('.benefit',{autoAlpha:0,y:50,stagger:.12,duration:.75,scrollTrigger:{trigger:'.benefits',start:'top 70%'}})
   const story=gsap.timeline({scrollTrigger:{trigger:'.value-story',start:'top top',end:'+=130%',pin:true,scrub:true}}); story.to('.value-one',{autoAlpha:0,y:-40}).fromTo('.value-two',{autoAlpha:0,y:35},{autoAlpha:1,y:0},'<').to('.value-two',{autoAlpha:0,y:-40},'+=.5').fromTo('.value-three',{autoAlpha:0,y:35},{autoAlpha:1,y:0},'<')
 },root); return()=>ctx.revert()},[])
 function updateSimulation(e: FormEvent){e.preventDefault(); gsap.fromTo('.sim-result',{scale:.96,autoAlpha:.5},{scale:1,autoAlpha:1,duration:.5,ease:'power3.out'}); gsap.fromTo('.bar-fill',{scaleX:.3},{scaleX:1,duration:.7,ease:'power3.out'})}
 return <main ref={root}>
  <nav className="nav"><a className="brand" href="#inicio"><strong>THIAGO</strong><span>ENERGIA SOLAR</span></a><div className="nav-links"><a href="#solucoes">Soluções</a><a href="#processo">Como funciona</a><a href="#beneficios">Benefícios</a><a href="#projetos">Projetos</a><a href="#faq">FAQ</a></div><a className="nav-cta" href="#simulador">Simular economia <b>↗</b></a></nav>
  <section className="hero" id="inicio"><div className="grid-bg"/><div className="hero-content"><p className="eyebrow hero-kicker">ENERGIA SOLAR PENSADA PARA A SUA REALIDADE</p><h1 className="hero-title"><span className="clip"><span className="line">Transforme o sol</span></span><span className="clip"><span className="line">em <em>economia.</em></span></span></h1><p className="hero-copy">Entenda o seu consumo, encontre uma solução adequada para o seu imóvel e comece a produzir sua própria energia.</p><div className="hero-actions"><a className="button" href="#simulador">Quero entender meu potencial <span>→</span></a><a className="text-link" href="#solucoes">Conhecer a solução <span>↓</span></a></div></div><div className="scene-wrap"><EnergyScene/></div><p className="scroll-hint">ROLE PARA DESCOBRIR <i/></p></section>
  <section className="problem section" id="solucoes"><div><p className="eyebrow reveal">UMA DESPESA QUE PODE VIRAR INVESTIMENTO</p><h2 className="reveal">Sua conta de energia<br/>não precisa ser só <em>despesa.</em></h2></div><div className="problem-side reveal"><p>Você paga pela energia todos os meses. A energia solar permite transformar parte desse gasto em geração própria, com uma solução pensada para o seu consumo e para o seu imóvel.</p><div className="problem-number"><strong>12</strong><sup>x</sup><span>uma despesa que faz parte da sua rotina e que pode ser repensada com energia solar.</span></div></div></section>
  <section className="value-story"><div className="value-header"><p className="eyebrow">O QUE MUDA QUANDO VOCÊ PRODUZ A PRÓPRIA ENERGIA</p><span>01—03</span></div><article className="value-item value-one"><p>01</p><h2>Você não está comprando<br/>apenas painéis. Está buscando <em>mais controle.</em></h2><span>ECONOMIA</span><small>Produza sua própria energia e reduza o peso da conta de luz no orçamento.</small></article><article className="value-item value-two hidden"><p>02</p><h2>Uma despesa menor.<br/>Uma relação mais <em>previsível.</em></h2><span>PREVISIBILIDADE</span><small>Mais clareza para planejar uma despesa que faz parte da sua rotina.</small></article><article className="value-item value-three hidden"><p>03</p><h2>Uma solução pensada<br/>para o seu <em>imóvel.</em></h2><span>VALOR</span><small>O projeto considera o consumo e as características do imóvel antes da instalação.</small></article><div className="value-orbit"><i/><i/><b>☀</b></div></section>
  <section className="energy-story"><div className="energy-copy"><p className="eyebrow">COMO A ENERGIA CHEGA ATÉ VOCÊ</p><h2>Do sol à<br/><em>sua energia.</em></h2><p>Da captação da luz solar à utilização no imóvel, cada etapa faz parte de um sistema que precisa ser bem dimensionado.</p><div className="energy-states"><span>01 CAPTAÇÃO</span><span>02 GERAÇÃO</span><span>03 CONVERSÃO</span><span>04 CONSUMO</span><span>05 ECONOMIA</span></div></div><div className="energy-scene"><EnergyScene detail/></div></section>
  <section className="process section" id="processo"><p className="eyebrow reveal">UM PROCESSO CLARO, DO PRIMEIRO CONTATO À GERAÇÃO</p><h2 className="reveal">Entenda cada etapa<br/>antes de <em>decidir.</em></h2><div className="process-line"/><div className="process-steps">{[['01','Análise','Entender o consumo e as características do imóvel.'],['02','Projeto','Definir uma solução de acordo com a necessidade identificada.'],['03','Instalação','Colocar o projeto em prática de forma organizada.'],['04','Geração','O sistema passa a produzir energia para o imóvel.']].map(x=><article className="process-step" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <section className="simulator section" id="simulador"><div className="sim-copy"><p className="eyebrow">SIMULAÇÃO INICIAL</p><h2>Quer descobrir o potencial de <em>economia?</em></h2><p>Informe alguns dados do seu consumo e do imóvel para ter uma primeira referência.</p></div><form onSubmit={updateSimulation}><label>Consumo mensal <div className="range-value">{consumption} kWh</div><input type="range" min="200" max="1800" step="50" value={consumption} onChange={e=>setConsumption(+e.target.value)}/></label><label>Tipo de imóvel<select value={property} onChange={e=>setProperty(e.target.value)}><option>Residencial</option><option>Comercial</option><option>Industrial</option></select></label><label>Cidade<select value={city} onChange={e=>setCity(e.target.value)}><option>São Paulo</option><option>Campinas</option><option>Santos</option></select></label><button className="button">Ver estimativa <span>→</span></button></form><div className="sim-result"><div className="result-main"><span>Estimativa mensal</span><strong>R$ {estimate.toLocaleString('pt-BR')}</strong><div className="chart"><i className="bar-fill" style={{width:`${Math.min(88,25+consumption/24)}%`}}/></div></div><div><span>Estimativa anual</span><b>R$ {annual.toLocaleString('pt-BR')}</b></div><div><span>Perfil</span><b>{property}</b></div><small>Esta é uma estimativa inicial. O resultado real depende do consumo, localização, tarifa e dimensionamento do sistema.</small><a className="text-link" href="#contato">Quero uma análise do meu imóvel <span>↗</span></a></div></section>
  <section className="benefits" id="beneficios"><div className="benefits-heading"><p className="eyebrow">O QUE VOCÊ BUSCA QUANDO ESCOLHE ENERGIA SOLAR</p><h2>Mais do que<br/><em>energia.</em></h2></div><div className="benefit-list">{['Economia na conta de energia','Geração própria','Mais previsibilidade','Tecnologia','Aproveitamento da energia solar','Uma solução pensada para o imóvel'].map((b,i)=><div className="benefit" key={b}><span>0{i+1}</span><strong>{b}</strong><i>↗</i></div>)}</div></section>
  <section className="projects section" id="projetos"><p className="eyebrow reveal">SOLUÇÕES PARA DIFERENTES NECESSIDADES</p><h2 className="reveal">Energia solar pensada<br/>para cada <em>realidade.</em></h2><div className="project-tabs">{Object.keys(projects).map(p=><button className={activeProject===p?'active':''} onClick={()=>setActiveProject(p as keyof typeof projects)} key={p}>{p}</button>)}</div><article className="project-display"><div className={'project-image '+activeProject.toLowerCase()}><div className="project-backdrop" aria-hidden="true"><Image src={`/projects/${activeProject.toLowerCase()}.jpg`} alt="" fill sizes="(max-width: 760px) 100vw, 58vw" className="project-backdrop-photo" /></div><div className="project-media"><Image src={`/projects/${activeProject.toLowerCase()}.jpg`} alt={`Projeto de energia solar ${activeProject.toLowerCase()}`} fill sizes="(max-width: 760px) 72vw, 38vw" className="project-photo" priority /></div><span>TES</span><i/></div><div className="project-info"><p>{projects[activeProject][1]}</p><h3>{projects[activeProject][0]}</h3><span>{projects[activeProject][2]}</span><a href="#contato" className="text-link">Quero entender essa solução <b>→</b></a></div></article></section>
  <section className="engineering section"><p className="eyebrow">ANTES DE INSTALAR, É PRECISO ENTENDER</p><h2>Uma boa solução começa<br/>antes da <em>instalação.</em></h2><div className="flow">{['Análise','Dimensionamento','Projeto','Instalação','Acompanhamento'].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b></div>)}</div></section>
  <section className="monitor section"><div><p className="eyebrow">ACOMPANHE O DESEMPENHO DO SISTEMA</p><h2>Energia sob<br/><em>controle.</em></h2><p>Uma visão simples dos dados de geração para entender melhor o que o seu sistema está produzindo.</p></div><div className="dashboard"><div className="dash-top"><span>GERAÇÃO</span><b>8.4 kWh</b><i>● DEMONSTRATIVO</i></div><svg viewBox="0 0 400 170" aria-label="Gráfico demonstrativo de geração"><path d="M0 150 C35 145 50 108 82 120 S120 77 152 92 S200 35 228 61 S275 49 303 78 S350 12 400 25" fill="none" stroke="#ffc94d" strokeWidth="3"/><path d="M0 150 C35 145 50 108 82 120 S120 77 152 92 S200 35 228 61 S275 49 303 78 S350 12 400 25 V170 H0 Z" fill="url(#g)" opacity=".4"/><defs><linearGradient id="g" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#ffc94d"/><stop offset="1" stopColor="#ffc94d" stopOpacity="0"/></linearGradient></defs></svg><div className="dash-bottom"><span>CONSUMO <b>3.1 kWh</b></span><span>ECONOMIA <b>R$ {estimate}</b></span><span>DESEMPENHO <b>98.6%</b></span></div></div></section>
  <section className="testimonials section"><p className="eyebrow">UMA DECISÃO QUE COMEÇA COM CLAREZA</p><h2>Antes de fechar,<br/><em>entenda o que está comprando.</em></h2><div className="quotes"><article><p>“Cada imóvel tem uma realidade diferente. Por isso, a solução precisa partir do consumo e das características do local.”</p><span>Thiago Energia Solar</span><small>Análise e dimensionamento</small></article><article><p>“Energia solar é um investimento de longo prazo. A decisão fica mais simples quando você entende como a solução foi pensada.”</p><span>Thiago Energia Solar</span><small>Orientação ao cliente</small></article></div></section>
  <section className="faq section" id="faq"><p className="eyebrow">ANTES DE COMEÇAR, ALGUMAS RESPOSTAS</p><h2>O que você precisa<br/><em>entender?</em></h2><div className="faq-list">{faqs.map((q,i)=><button key={q} className={open===i?'open':''} onClick={()=>setOpen(open===i?null:i)}><span>{q}</span><b>{open===i?'−':'+'}</b><p>{i===0?'Pode reduzir a conta de energia, mas o resultado depende do consumo, da tarifa, da localização, das condições do imóvel e do dimensionamento do sistema. Por isso, a análise do caso é importante.':i===1?'O investimento varia conforme o consumo, o imóvel e a solução necessária. Depois de entender esses fatores, é possível avaliar uma proposta adequada.':i===2?'As condições do imóvel precisam ser avaliadas para entender a viabilidade e o dimensionamento da solução.':i===3?'A manutenção e o acompanhamento dependem dos equipamentos e da solução instalada. Esses pontos devem ser explicados durante a apresentação do projeto.':i===4?'Sim. Os módulos continuam gerando energia com a radiação solar disponível, embora a produção possa ser menor em dias nublados.':'O sistema é definido a partir de informações como consumo, localização e características do imóvel. A ideia é dimensionar uma solução adequada ao caso.'}</p></button>)}</div></section>
  <section className="final-cta" id="contato"><div><p className="eyebrow">O PRÓXIMO PASSO É SIMPLES</p><h2>Descubra o que a energia solar pode fazer pelo <em>seu imóvel.</em></h2><p>Conte um pouco sobre seu consumo e seu imóvel. A partir dessas informações, podemos entender melhor qual solução faz sentido para você.</p><div className="hero-actions"><a className="button" href="mailto:contato@thiagoenergia.com">Quero entender meu potencial <span>→</span></a><a className="text-link" href="mailto:contato@thiagoenergia.com">Falar sobre meu imóvel <span>↗</span></a></div></div><div className="final-scene"><EnergyScene detail/></div></section>
  <footer><a className="brand" href="#inicio"><strong>THIAGO</strong><span>ENERGIA SOLAR</span></a><div><a href="#solucoes">Soluções</a><a href="#projetos">Projetos</a><a href="#faq">FAQ</a><a href="mailto:contato@thiagoenergia.com">Contato</a></div><p>© 2026 Thiago Energia Solar. As informações e estimativas apresentadas podem variar conforme o consumo, o imóvel e o dimensionamento do sistema.</p></footer>
 </main>
}
